"""Component B, first half: read and write MO2's ``modlist.txt``.

MO2 stores the left pane highest-priority-first, so the top line of the file
is the mod that wins every conflict.  Everything inside this package works in
priority order instead - index 0 loads first and is overridden by everything
below it - and the two conversions live here, in one place, so no other module
has to remember which way round the file is.

The leading ``+``/``-``/``*`` is the entry's state, not decoration: ``+`` is
enabled, ``-`` disabled, ``*`` is content MO2 does not manage (the base game's
DLC and Creation Club).  It is carried through untouched and reattached on the
way out.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field

from . import backups

SEPARATOR_SUFFIX = "_separator"
PREFIXES = "+-*"


@dataclass
class ModNode:
    name: str
    prefix: str                       # "+", "-" or "*"
    original_index: int               # position in priority order, as read
    nexus_id: int | None = None
    file_date: str = ""            # nexusLastModified, for the resolve dialog
    version: str = ""
    mo2_categories: list = field(default_factory=list)
    tier: int = 3
    subtier: int = 0               # orders texture mods inside a tier
    category_name: str = ""
    is_tool: bool = False          # run, not loaded: emits no edges
    tier_reason: str = ""
    file_manifest: list[str] = field(default_factory=list)
    plugins: list[str] = field(default_factory=list)
    masters: list[str] = field(default_factory=list)

    @property
    def enabled(self) -> bool:
        return self.prefix != "-"

    @property
    def is_separator(self) -> bool:
        return self.name.endswith(SEPARATOR_SUFFIX)

    @property
    def is_unmanaged(self) -> bool:
        """DLC, Creation Club and Creations-store entries.

        MO2 pins these above everything else in the left pane and refuses to
        move them, so they are read, kept in place and written back out
        exactly where they were - sorting them would produce a file MO2 will
        not honour.
        """
        return self.prefix == "*"


def read_modlist(path: str) -> tuple[list[ModNode], list[str]]:
    """(nodes in priority order, header comment lines).

    Index 0 loads first and the last node wins.  The comments come back too:
    MO2 writes "# This file was automatically generated by Mod Organizer." at
    the top of every profile it owns, and a sorter that quietly dropped it
    would leave the file looking hand-edited.
    """
    rows: list[tuple[str, str]] = []
    header: list[str] = []
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.rstrip()
            if not line:
                continue
            if line.startswith("#"):
                header.append(line)
                continue
            if line[0] not in PREFIXES:
                continue
            rows.append((line[0], line[1:]))
    rows.reverse()
    nodes = [ModNode(name=name, prefix=prefix, original_index=i)
             for i, (prefix, name) in enumerate(rows)]
    return nodes, header


def serialise(nodes: list[ModNode], header: list[str] | None = None) -> str:
    """The file body for ``nodes`` given in priority order."""
    out = ["{}\n".format(c) for c in (header or [])]
    out += ["{}{}\n".format(n.prefix, n.name) for n in reversed(nodes)]
    return "".join(out)


def write_modlist(path: str, nodes: list[ModNode],
                  header: list[str] | None = None,
                  backup: bool = True, label: str = "") -> str | None:
    """Write the list back, keeping a dated copy of what was there before.

    Written to a temporary file in the same directory and moved into place, so
    an interrupted write cannot leave MO2 with half a mod list.  The backup is
    taken first and kept for ever after (up to a limit), because it is the
    only route back to a list the user built by hand.
    """
    saved = None
    if backup and os.path.isfile(path):
        saved = backups.make(path, label)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(serialise(nodes, header))
    os.replace(tmp, path)
    return saved
